module.exports = [
  {
    id: "philae_temple",
    name: "Philae Temple",
    cityId: "aswan",
    categories: ["History", "Photography"],
    visitDuration: 150,
    ticketPrice: 500,
    rating: 4.9,
    location: { latitude: 24.0258, longitude: 32.8849 },
    openingTime: "07:00",
    closingTime: "17:00",
    priority: 10,
    imageUrl: "",
    description: "Ancient temple dedicated to the goddess Isis."
  },
  {
    id: "high_dam",
    name: "Aswan High Dam",
    cityId: "aswan",
    categories: ["History"],
    visitDuration: 90,
    ticketPrice: 150,
    rating: 4.6,
    location: { latitude: 23.9707, longitude: 32.8774 },
    openingTime: "08:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "One of Egypt's greatest engineering achievements."
  },
  {
    id: "unfinished_obelisk",
    name: "Unfinished Obelisk",
    cityId: "aswan",
    categories: ["History"],
    visitDuration: 60,
    ticketPrice: 200,
    rating: 4.6,
    location: { latitude: 24.0827, longitude: 32.8998 },
    openingTime: "07:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "Largest known ancient obelisk."
  },
  {
    id: "nubian_museum",
    name: "Nubian Museum",
    cityId: "aswan",
    categories: ["Museum", "History"],
    visitDuration: 120,
    ticketPrice: 300,
    rating: 4.8,
    location: { latitude: 24.0795, longitude: 32.8877 },
    openingTime: "09:00",
    closingTime: "21:00",
    priority: 9,
    imageUrl: "",
    description: "Museum showcasing Nubian civilization."
  },
  {
    id: "elephantine_island",
    name: "Elephantine Island",
    cityId: "aswan",
    categories: ["Nature", "History"],
    visitDuration: 120,
    ticketPrice: 100,
    rating: 4.7,
    location: { latitude: 24.0895, longitude: 32.8898 },
    openingTime: "08:00",
    closingTime: "18:00",
    priority: 8,
    imageUrl: "",
    description: "Historic island on the Nile."
  },
  {
    id: "botanical_garden",
    name: "Aswan Botanical Garden",
    cityId: "aswan",
    categories: ["Nature", "Family"],
    visitDuration: 120,
    ticketPrice: 100,
    rating: 4.7,
    location: { latitude: 24.0951, longitude: 32.8797 },
    openingTime: "08:00",
    closingTime: "17:00",
    priority: 7,
    imageUrl: "",
    description: "Beautiful botanical island."
  },
  {
    id: "nubian_village",
    name: "Nubian Village",
    cityId: "aswan",
    categories: ["Food", "Shopping", "Photography"],
    visitDuration: 180,
    ticketPrice: 200,
    rating: 4.8,
    location: { latitude: 24.0628, longitude: 32.8870 },
    openingTime: "09:00",
    closingTime: "20:00",
    priority: 9,
    imageUrl: "",
    description: "Traditional colorful Nubian village."
  },
  {
    id: "aga_khan_mausoleum",
    name: "Aga Khan Mausoleum",
    cityId: "aswan",
    categories: ["History"],
    visitDuration: 60,
    ticketPrice: 100,
    rating: 4.5,
    location: { latitude: 24.0882, longitude: 32.8753 },
    openingTime: "09:00",
    closingTime: "17:00",
    priority: 6,
    imageUrl: "",
    description: "Historic mausoleum overlooking the Nile."
  },
  {
    id: "kalabsha_temple",
    name: "Kalabsha Temple",
    cityId: "aswan",
    categories: ["History"],
    visitDuration: 120,
    ticketPrice: 300,
    rating: 4.8,
    location: { latitude: 23.9974, longitude: 32.8598 },
    openingTime: "08:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "Ancient Nubian temple relocated after the High Dam."
  },
  {
    id: "kom_ombo_temple",
    name: "Kom Ombo Temple",
    cityId: "aswan",
    categories: ["History", "Photography"],
    visitDuration: 120,
    ticketPrice: 300,
    rating: 4.8,
    location: { latitude: 24.4523, longitude: 32.9285 },
    openingTime: "07:00",
    closingTime: "17:00",
    priority: 9,
    imageUrl: "",
    description: "Unique double temple dedicated to Sobek and Horus."
  },
  {
    id: "edfu_temple",
    name: "Edfu Temple",
    cityId: "aswan",
    categories: ["History"],
    visitDuration: 120,
    ticketPrice: 300,
    rating: 4.9,
    location: { latitude: 24.9779, longitude: 32.8742 },
    openingTime: "07:00",
    closingTime: "17:00",
    priority: 9,
    imageUrl: "",
    description: "Best-preserved temple in Egypt."
  },
  {
    id: "lake_nasser",
    name: "Lake Nasser",
    cityId: "aswan",
    categories: ["Nature", "Photography"],
    visitDuration: 120,
    ticketPrice: 0,
    rating: 4.7,
    location: { latitude: 23.7000, longitude: 32.9000 },
    openingTime: "00:00",
    closingTime: "23:59",
    priority: 7,
    imageUrl: "",
    description: "One of the world's largest artificial lakes."
  },
  {
    id: "saint_simeon_monastery",
    name: "Saint Simeon Monastery",
    cityId: "aswan",
    categories: ["History"],
    visitDuration: 120,
    ticketPrice: 150,
    rating: 4.6,
    location: { latitude: 24.0998, longitude: 32.8736 },
    openingTime: "08:00",
    closingTime: "16:00",
    priority: 7,
    imageUrl: "",
    description: "Ancient Coptic monastery."
  },
  {
    id: "aswan_corniche",
    name: "Aswan Corniche",
    cityId: "aswan",
    categories: ["Food", "Nature", "Photography"],
    visitDuration: 90,
    ticketPrice: 0,
    rating: 4.7,
    location: { latitude: 24.0908, longitude: 32.8995 },
    openingTime: "00:00",
    closingTime: "23:59",
    priority: 6,
    imageUrl: "",
    description: "Beautiful Nile promenade."
  },
  {
    id: "aswan_museum",
    name: "Aswan Museum",
    cityId: "aswan",
    categories: ["Museum", "History"],
    visitDuration: 90,
    ticketPrice: 200,
    rating: 4.6,
    location: { latitude: 24.0889, longitude: 32.8892 },
    openingTime: "09:00",
    closingTime: "17:00",
    priority: 7,
    imageUrl: "",
    description: "Museum displaying Nubian and Egyptian antiquities."
  }
];