module.exports = [
  {
    id: "egyptian_museum",
    name: "Egyptian Museum",
    cityId: "cairo",
    categories: ["History", "Museum", "Photography"],
    visitDuration: 150,
    ticketPrice: 500,
    rating: 4.8,
    location: { latitude: 30.047778, longitude: 31.233611 },
    openingTime: "09:00",
    closingTime: "17:00",
    priority: 10,
    imageUrl: "",
    description: "The oldest archaeological museum in Egypt."
  },
  {
    id: "nmec",
    name: "National Museum of Egyptian Civilization",
    cityId: "cairo",
    categories: ["Museum", "History"],
    visitDuration: 120,
    ticketPrice: 500,
    rating: 4.8,
    location: { latitude: 30.0061, longitude: 31.2470 },
    openingTime: "09:00",
    closingTime: "17:00",
    priority: 9,
    imageUrl: "",
    description: "Museum showcasing Egypt's civilization."
  },
  {
    id: "cairo_citadel",
    name: "Cairo Citadel",
    cityId: "cairo",
    categories: ["History", "Photography"],
    visitDuration: 120,
    ticketPrice: 300,
    rating: 4.7,
    location: { latitude: 30.0287, longitude: 31.2599 },
    openingTime: "08:00",
    closingTime: "17:00",
    priority: 9,
    imageUrl: "",
    description: "Historic Islamic fortress."
  },
  {
    id: "mohamed_ali_mosque",
    name: "Mosque of Muhammad Ali",
    cityId: "cairo",
    categories: ["History", "Photography"],
    visitDuration: 60,
    ticketPrice: 0,
    rating: 4.8,
    location: { latitude: 30.0292, longitude: 31.2598 },
    openingTime: "08:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "Iconic Ottoman mosque."
  },
  {
    id: "sultan_hassan_mosque",
    name: "Sultan Hassan Mosque",
    cityId: "cairo",
    categories: ["History"],
    visitDuration: 45,
    ticketPrice: 100,
    rating: 4.7,
    location: { latitude: 30.0296, longitude: 31.2578 },
    openingTime: "09:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "Historic Mamluk mosque."
  },
  {
    id: "al_refai_mosque",
    name: "Al-Rifa'i Mosque",
    cityId: "cairo",
    categories: ["History"],
    visitDuration: 45,
    ticketPrice: 100,
    rating: 4.6,
    location: { latitude: 30.0299, longitude: 31.2576 },
    openingTime: "09:00",
    closingTime: "17:00",
    priority: 7,
    imageUrl: "",
    description: "Historic royal mosque."
  },
  {
    id: "al_muizz_street",
    name: "Al-Muizz Street",
    cityId: "cairo",
    categories: ["History", "Shopping", "Photography", "Food"],
    visitDuration: 120,
    ticketPrice: 0,
    rating: 4.8,
    location: { latitude: 30.0508, longitude: 31.2625 },
    openingTime: "00:00",
    closingTime: "23:59",
    priority: 10,
    imageUrl: "",
    description: "Historic street full of Islamic monuments."
  },
  {
    id: "khan_el_khalili",
    name: "Khan El Khalili",
    cityId: "cairo",
    categories: ["Shopping", "Food", "Photography"],
    visitDuration: 120,
    ticketPrice: 0,
    rating: 4.7,
    location: { latitude: 30.0478, longitude: 31.2625 },
    openingTime: "09:00",
    closingTime: "23:00",
    priority: 10,
    imageUrl: "",
    description: "Famous traditional bazaar."
  },
  {
    id: "bab_zuweila",
    name: "Bab Zuweila",
    cityId: "cairo",
    categories: ["History", "Photography"],
    visitDuration: 45,
    ticketPrice: 100,
    rating: 4.6,
    location: { latitude: 30.0456, longitude: 31.2574 },
    openingTime: "09:00",
    closingTime: "17:00",
    priority: 7,
    imageUrl: "",
    description: "Historic gate of Cairo."
  },
  {
    id: "bayt_al_suhaymi",
    name: "Bayt Al-Suhaymi",
    cityId: "cairo",
    categories: ["History"],
    visitDuration: 60,
    ticketPrice: 100,
    rating: 4.6,
    location: { latitude: 30.0528, longitude: 31.2623 },
    openingTime: "09:00",
    closingTime: "17:00",
    priority: 7,
    imageUrl: "",
    description: "Historic Ottoman house."
  },
  {
    id: "al_azhar_park",
    name: "Al Azhar Park",
    cityId: "cairo",
    categories: ["Nature", "Photography", "Family"],
    visitDuration: 120,
    ticketPrice: 50,
    rating: 4.7,
    location: { latitude: 30.0403, longitude: 31.2688 },
    openingTime: "09:00",
    closingTime: "22:00",
    priority: 8,
    imageUrl: "",
    description: "Large public park overlooking Cairo."
  },
  {
    id: "abdeen_palace",
    name: "Abdeen Palace",
    cityId: "cairo",
    categories: ["History", "Museum"],
    visitDuration: 120,
    ticketPrice: 200,
    rating: 4.5,
    location: { latitude: 30.0444, longitude: 31.2453 },
    openingTime: "09:00",
    closingTime: "15:00",
    priority: 7,
    imageUrl: "",
    description: "Historic presidential palace."
  },
  {
    id: "manial_palace",
    name: "Manial Palace",
    cityId: "cairo",
    categories: ["History", "Museum", "Photography"],
    visitDuration: 120,
    ticketPrice: 200,
    rating: 4.8,
    location: { latitude: 30.0182, longitude: 31.2289 },
    openingTime: "09:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "Prince Mohamed Ali Palace."
  },
  {
    id: "cairo_tower",
    name: "Cairo Tower",
    cityId: "cairo",
    categories: ["Photography"],
    visitDuration: 60,
    ticketPrice: 300,
    rating: 4.6,
    location: { latitude: 30.0459, longitude: 31.2243 },
    openingTime: "09:00",
    closingTime: "23:00",
    priority: 8,
    imageUrl: "",
    description: "Observation tower with panoramic views."
  },
  {
    id: "coptic_cairo",
    name: "Coptic Cairo",
    cityId: "cairo",
    categories: ["History", "Photography"],
    visitDuration: 120,
    ticketPrice: 0,
    rating: 4.8,
    location: { latitude: 30.0062, longitude: 31.2303 },
    openingTime: "09:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "Historic Christian district."
  }
];