module.exports = [
  {
    id: "pyramids_of_giza",
    name: "Pyramids of Giza",
    cityId: "giza",
    categories: ["History", "Photography"],
    visitDuration: 180,
    ticketPrice: 500,
    rating: 4.9,
    location: { latitude: 29.9792, longitude: 31.1342 },
    openingTime: "08:00",
    closingTime: "17:00",
    priority: 10,
    imageUrl: "",
    description: "The last remaining wonder of the ancient world."
  },
  {
    id: "great_sphinx",
    name: "Great Sphinx",
    cityId: "giza",
    categories: ["History", "Photography"],
    visitDuration: 60,
    ticketPrice: 0,
    rating: 4.8,
    location: { latitude: 29.9753, longitude: 31.1376 },
    openingTime: "08:00",
    closingTime: "17:00",
    priority: 10,
    imageUrl: "",
    description: "The iconic limestone statue guarding the pyramids."
  },
  {
    id: "panorama_point",
    name: "Panorama Point",
    cityId: "giza",
    categories: ["Photography"],
    visitDuration: 45,
    ticketPrice: 0,
    rating: 4.8,
    location: { latitude: 29.9728, longitude: 31.1287 },
    openingTime: "08:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "Best panoramic view of the pyramids."
  },
  {
    id: "khufu_boat_museum",
    name: "Khufu Boat Museum",
    cityId: "giza",
    categories: ["Museum", "History"],
    visitDuration: 60,
    ticketPrice: 300,
    rating: 4.7,
    location: { latitude: 29.9795, longitude: 31.1345 },
    openingTime: "09:00",
    closingTime: "16:00",
    priority: 8,
    imageUrl: "",
    description: "Museum displaying the reconstructed solar boat."
  },
  {
    id: "saqqara",
    name: "Saqqara",
    cityId: "giza",
    categories: ["History", "Photography"],
    visitDuration: 180,
    ticketPrice: 400,
    rating: 4.8,
    location: { latitude: 29.8711, longitude: 31.2165 },
    openingTime: "08:00",
    closingTime: "17:00",
    priority: 9,
    imageUrl: "",
    description: "Ancient necropolis containing the Step Pyramid."
  },
  {
    id: "step_pyramid",
    name: "Step Pyramid of Djoser",
    cityId: "giza",
    categories: ["History"],
    visitDuration: 60,
    ticketPrice: 0,
    rating: 4.8,
    location: { latitude: 29.8713, longitude: 31.2164 },
    openingTime: "08:00",
    closingTime: "17:00",
    priority: 9,
    imageUrl: "",
    description: "The world's oldest monumental stone structure."
  },
  {
    id: "dahshur",
    name: "Dahshur",
    cityId: "giza",
    categories: ["History", "Photography"],
    visitDuration: 120,
    ticketPrice: 300,
    rating: 4.7,
    location: { latitude: 29.7995, longitude: 31.2055 },
    openingTime: "08:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "Royal necropolis south of Saqqara."
  },
  {
    id: "red_pyramid",
    name: "Red Pyramid",
    cityId: "giza",
    categories: ["History"],
    visitDuration: 60,
    ticketPrice: 0,
    rating: 4.8,
    location: { latitude: 29.8086, longitude: 31.2058 },
    openingTime: "08:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "Egypt's first successful true pyramid."
  },
  {
    id: "bent_pyramid",
    name: "Bent Pyramid",
    cityId: "giza",
    categories: ["History"],
    visitDuration: 60,
    ticketPrice: 0,
    rating: 4.7,
    location: { latitude: 29.7903, longitude: 31.2095 },
    openingTime: "08:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "Unique pyramid with a bent angle."
  },
  {
    id: "pharaonic_village",
    name: "Pharaonic Village",
    cityId: "giza",
    categories: ["History", "Family"],
    visitDuration: 180,
    ticketPrice: 350,
    rating: 4.5,
    location: { latitude: 29.9982, longitude: 31.2120 },
    openingTime: "09:00",
    closingTime: "17:00",
    priority: 7,
    imageUrl: "",
    description: "Living museum recreating ancient Egyptian life."
  },
  {
    id: "orman_garden",
    name: "Orman Garden",
    cityId: "giza",
    categories: ["Nature", "Family"],
    visitDuration: 120,
    ticketPrice: 50,
    rating: 4.5,
    location: { latitude: 30.0270, longitude: 31.2132 },
    openingTime: "09:00",
    closingTime: "17:00",
    priority: 6,
    imageUrl: "",
    description: "Historic botanical garden."
  },
  {
    id: "giza_zoo",
    name: "Giza Zoo",
    cityId: "giza",
    categories: ["Family", "Nature"],
    visitDuration: 180,
    ticketPrice: 100,
    rating: 4.4,
    location: { latitude: 30.0278, longitude: 31.2145 },
    openingTime: "09:00",
    closingTime: "17:00",
    priority: 6,
    imageUrl: "",
    description: "One of Africa's oldest zoos."
  }
];