module.exports = [
  {
    id: "karnak_temple",
    name: "Karnak Temple",
    cityId: "luxor",
    categories: ["History", "Photography"],
    visitDuration: 180,
    ticketPrice: 500,
    rating: 4.9,
    location: { latitude: 25.7188, longitude: 32.6573 },
    openingTime: "06:00",
    closingTime: "17:30",
    priority: 10,
    imageUrl: "",
    description: "The largest religious complex ever built."
  },
  {
    id: "luxor_temple",
    name: "Luxor Temple",
    cityId: "luxor",
    categories: ["History", "Photography"],
    visitDuration: 120,
    ticketPrice: 400,
    rating: 4.9,
    location: { latitude: 25.6996, longitude: 32.6396 },
    openingTime: "06:00",
    closingTime: "22:00",
    priority: 10,
    imageUrl: "",
    description: "Ancient temple in the heart of Luxor."
  },
  {
    id: "valley_of_the_kings",
    name: "Valley of the Kings",
    cityId: "luxor",
    categories: ["History"],
    visitDuration: 180,
    ticketPrice: 600,
    rating: 4.9,
    location: { latitude: 25.7402, longitude: 32.6014 },
    openingTime: "06:00",
    closingTime: "17:00",
    priority: 10,
    imageUrl: "",
    description: "Royal burial site of New Kingdom pharaohs."
  },
  {
    id: "hatshepsut_temple",
    name: "Temple of Hatshepsut",
    cityId: "luxor",
    categories: ["History", "Photography"],
    visitDuration: 120,
    ticketPrice: 400,
    rating: 4.8,
    location: { latitude: 25.7382, longitude: 32.6067 },
    openingTime: "06:00",
    closingTime: "17:00",
    priority: 9,
    imageUrl: "",
    description: "Mortuary temple of Queen Hatshepsut."
  },
  {
    id: "colossi_of_memnon",
    name: "Colossi of Memnon",
    cityId: "luxor",
    categories: ["History"],
    visitDuration: 30,
    ticketPrice: 0,
    rating: 4.6,
    location: { latitude: 25.7206, longitude: 32.6105 },
    openingTime: "00:00",
    closingTime: "23:59",
    priority: 7,
    imageUrl: "",
    description: "Two massive stone statues of Amenhotep III."
  },
  {
    id: "medinet_habu",
    name: "Medinet Habu",
    cityId: "luxor",
    categories: ["History"],
    visitDuration: 120,
    ticketPrice: 250,
    rating: 4.8,
    location: { latitude: 25.7191, longitude: 32.6004 },
    openingTime: "06:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "Temple of Ramesses III."
  },
  {
    id: "ramesseum",
    name: "Ramesseum",
    cityId: "luxor",
    categories: ["History"],
    visitDuration: 90,
    ticketPrice: 200,
    rating: 4.7,
    location: { latitude: 25.7244, longitude: 32.6060 },
    openingTime: "06:00",
    closingTime: "17:00",
    priority: 7,
    imageUrl: "",
    description: "Mortuary temple of Ramesses II."
  },
  {
    id: "valley_of_the_queens",
    name: "Valley of the Queens",
    cityId: "luxor",
    categories: ["History"],
    visitDuration: 120,
    ticketPrice: 300,
    rating: 4.8,
    location: { latitude: 25.7273, longitude: 32.5944 },
    openingTime: "06:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "Burial site of queens and princes."
  },
  {
    id: "luxor_museum",
    name: "Luxor Museum",
    cityId: "luxor",
    categories: ["Museum", "History"],
    visitDuration: 120,
    ticketPrice: 300,
    rating: 4.8,
    location: { latitude: 25.7097, longitude: 32.6446 },
    openingTime: "09:00",
    closingTime: "21:00",
    priority: 8,
    imageUrl: "",
    description: "Museum of ancient Egyptian artifacts."
  },
  {
    id: "mummification_museum",
    name: "Mummification Museum",
    cityId: "luxor",
    categories: ["Museum", "History"],
    visitDuration: 60,
    ticketPrice: 200,
    rating: 4.6,
    location: { latitude: 25.7042, longitude: 32.6397 },
    openingTime: "09:00",
    closingTime: "21:00",
    priority: 7,
    imageUrl: "",
    description: "Museum explaining mummification."
  },
  {
    id: "deir_el_medina",
    name: "Deir el-Medina",
    cityId: "luxor",
    categories: ["History"],
    visitDuration: 120,
    ticketPrice: 250,
    rating: 4.8,
    location: { latitude: 25.7338, longitude: 32.6019 },
    openingTime: "06:00",
    closingTime: "17:00",
    priority: 8,
    imageUrl: "",
    description: "Ancient workers' village."
  },
  {
    id: "tombs_of_the_nobles",
    name: "Tombs of the Nobles",
    cityId: "luxor",
    categories: ["History"],
    visitDuration: 120,
    ticketPrice: 200,
    rating: 4.7,
    location: { latitude: 25.7218, longitude: 32.6287 },
    openingTime: "06:00",
    closingTime: "17:00",
    priority: 7,
    imageUrl: "",
    description: "Decorated tombs of ancient officials."
  },
  {
    id: "banana_island",
    name: "Banana Island",
    cityId: "luxor",
    categories: ["Nature", "Family"],
    visitDuration: 120,
    ticketPrice: 150,
    rating: 4.5,
    location: { latitude: 25.6885, longitude: 32.6292 },
    openingTime: "09:00",
    closingTime: "18:00",
    priority: 6,
    imageUrl: "",
    description: "Island famous for banana plantations."
  },
  {
    id: "avenue_of_sphinxes",
    name: "Avenue of Sphinxes",
    cityId: "luxor",
    categories: ["History", "Photography"],
    visitDuration: 60,
    ticketPrice: 0,
    rating: 4.8,
    location: { latitude: 25.7058, longitude: 32.6463 },
    openingTime: "00:00",
    closingTime: "23:59",
    priority: 8,
    imageUrl: "",
    description: "Ancient road connecting Karnak and Luxor Temple."
  },
  {
    id: "luxor_corniche",
    name: "Luxor Corniche",
    cityId: "luxor",
    categories: ["Nature", "Food", "Photography"],
    visitDuration: 60,
    ticketPrice: 0,
    rating: 4.7,
    location: { latitude: 25.6995, longitude: 32.6420 },
    openingTime: "00:00",
    closingTime: "23:59",
    priority: 6,
    imageUrl: "",
    description: "Scenic promenade along the Nile."
  }
];