// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT_JsEbe1_XcxqV3oPl8Lo6OgnaeG23Ok',
    appId: '1:641080345679:android:4d9d7f969d9664fbfa963a',
    messagingSenderId: '641080345679',
    projectId: 'dalil-86779',
    storageBucket: 'dalil-86779.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO14OFv4rvdKQzfoQimdFSGj5kqtKs7T8',
    appId: '1:641080345679:ios:625bfa35faaedce9fa963a',
    messagingSenderId: '641080345679',
    projectId: 'dalil-86779',
    storageBucket: 'dalil-86779.firebasestorage.app',
    androidClientId: '641080345679-5ibf6bs45lpaqu2fn960u51i26h53vpm.apps.googleusercontent.com',
    iosClientId: '641080345679-ao5n1lfmhld3foo7c042um4kuquvpi2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.dalil',
  );
}
